# Generated by Django 4.2.4 on 2024-01-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactModel',
        ),
    ]
